curl -o Heater-1.mp3 https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3 
curl -o Heater-2.mp3 https://s3.amazonaws.com/freecodecamp/drums/Heater-2.mp3 
curl -o Heater-3.mp3 https://s3.amazonaws.com/freecodecamp/drums/Heater-3.mp3 
curl -o Heater-4_1.mp3 https://s3.amazonaws.com/freecodecamp/drums/Heater-4_1.mp3 
curl -o Heater-6.mp3 https://s3.amazonaws.com/freecodecamp/drums/Heater-6.mp3 
curl -o Dsc_Oh.mp3 https://s3.amazonaws.com/freecodecamp/drums/Dsc_Oh.mp3 
curl -o Kick_n_Hat.mp3 https://s3.amazonaws.com/freecodecamp/drums/Kick_n_Hat.mp3 
curl -o RP4_KICK_1.mp3 https://s3.amazonaws.com/freecodecamp/drums/RP4_KICK_1.mp3 
curl -o Cev_H2.mp3 https://s3.amazonaws.com/freecodecamp/drums/Cev_H2.mp3 
curl -o Chord_1.mp3 https://s3.amazonaws.com/freecodecamp/drums/Chord_1.mp3 
curl -o Chord_2.mp3 https://s3.amazonaws.com/freecodecamp/drums/Chord_2.mp3 
curl -o Chord_3.mp3 https://s3.amazonaws.com/freecodecamp/drums/Chord_3.mp3 
curl -o Give_us_a_light.mp3 https://s3.amazonaws.com/freecodecamp/drums/Give_us_a_light.mp3 
curl -o Dry_Ohh.mp3 https://s3.amazonaws.com/freecodecamp/drums/Dry_Ohh.mp3 
curl -o Bld_H1.mp3 https://s3.amazonaws.com/freecodecamp/drums/Bld_H1.mp3 
curl -o punchy_kick_1.mp3 https://s3.amazonaws.com/freecodecamp/drums/punchy_kick_1.mp3 
curl -o side_stick_1.mp3 https://s3.amazonaws.com/freecodecamp/drums/side_stick_1.mp3 
curl -o Brk_Snr.mp3 https://s3.amazonaws.com/freecodecamp/drums/Brk_Snr.mp3 
